name = "quick-match"
main = "server.ts"
compatibility_date = "2024-01-24"

[[durable_objects.bindings]]
name = "Game"
class_name = "Game"

[[durable_objects.bindings]]
name = "Remix"
class_name = "Remix"

[[migrations]]
tag = "v1"
new_classes = ["Game"]

[[migrations]]
tag = "v1"
new_classes = ["Remix"]